title: Disability Improvements
author: Toni Blackwelder
email: tblackwelder@sbcglobal.net
description: > # this means to ignore newlines until "baseurl:"
  This site is designed to discuss ways to make life easier for 
  people with disabilities.

# social links
twitter_username: @tanya518
github_username:  @toni517b

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
